-- ===================================================================================================
-- 0179 . THE CRAFT / PROCESS STORY -- grounds the concierge (+ all agents) in HOW we make it
-- ===================================================================================================
-- 0178 taught the AI the ingredients; this teaches it the PROCESS -- the owner's "explaining the how
-- is important." Every row is web-sourced and stays in the one defensible register: process +
-- materials truth (what we source, test, and touch it with), never a body-outcome promise. Each row
-- carries its own MAY / MUST-NOT boundary so the AI self-polices. The final row is a hard negative
-- guardrail: it retires the "positively affects gene expression / net-positive on your genes" claim
-- from all outward copy (highest regulatory liability; human evidence is preliminary and mechanistic
-- only) and gives the compliant reframe. Idempotent by title.

insert into public.agent_knowledge (agent, title, body, author_name)
select v.agent, v.title, v.body, 'Craft process (researched)'
from (values
  ('concierge', 'Craft . The standard (keep the good, add nothing)',
   $b$Our whole approach: coffee and cocoa are powerful plants that, in animal-based circles, sit on a "be careful" list because plants carry plant-defense compounds (tannins, oxalates, caffeine/alkaloids; for coffee, a mold/mycotoxin consideration). We do not pretend that away -- we do the care most skip: careful origin sourcing, testing, low-heat extraction, and inert materials, so you get the good with the concerns minimized. MAY say: we take the care most do not; sourcing, testing, cold extraction, and inert materials minimize the concerns. MUST NOT say our process makes coffee/cocoa "carnivore-safe," "antinutrient-free," or "removes all plant toxins" (overclaim), and do not disparage plants in general. Frame as CARE, not CURE. Source: animal-based diet framing (Saladino); antinutrients overview.$b$),
  ('concierge', 'Craft . Sourced by origin + tested (never "toxin-free")',
   $b$A plant draws what its soil and drying give it, so origin is the first lever. Coffee can carry ochratoxin A (a mold compound) when grown/dried/stored damp; roasting itself degrades most of it and careful drying/storage prevents it forming. Cacao can pick up cadmium from soil and lead during outdoor drying. We source by origin and test to keep both clean and within accepted limits. MAY say: we source and test to keep mycotoxins and heavy metals low, within international limits; roasting and careful drying reduce mycotoxins; we do not rely on "organic" as a heavy-metals guarantee, we test. MUST NOT say "toxin-free," "mold-free," "mycotoxin-free," "heavy-metal-free," or "zero cadmium/lead" -- these are measured in micrograms, not proven absent; claim tested-low / within-limits, never zero. Do not tie any of this to a disease outcome, and do not claim other brands "are full of mold." Sources: JAFC 1998 (OTA roasting reduction); EU Reg 2022/1370; Consumer Reports 2023 + PMC11321977 (cocoa metals).$b$),
  ('concierge', 'Craft . Drawn cold (smoother, not "low-acid")',
   $b$We cold-extract: steeped slow in cool water for hours, never rushed with heat, which many people find smoother and less bitter -- the coffee giving its best character instead of its harshest. MAY say: smoother, less bitter, brewed without heat, gentler-tasting. MUST NOT say "low-acid," "acid-free," or "less acidic so easier on your stomach" -- measured pH is often similar to hot brew, so the honest claim is sensory (smoother/less bitter), not a chemistry or digestion claim. Source: Rao & Fuller, Scientific Reports (Nature) 2018.$b$),
  ('concierge', 'Craft . Poured into glass + stainless (the materials story)',
   $b$Every point the coffee touches is glass or food-grade stainless steel (304/316), chosen because they are inert -- they do not shed the bisphenols (BPA/BPS) or phthalate plasticizers that can migrate out of plastic with heat, acidity, and time, nor the microplastics associated with plastic contact surfaces. We control what is IN the bottle by controlling what it TOUCHES. MAY say: we use glass and food-grade stainless because they are inert -- no BPA, BPS, or phthalate plasticizers to migrate in; we choose materials that do not introduce those compounds. This is a MATERIALS/COMPOSITION statement -- the safe register. MUST NOT say "zero microplastics," "non-toxic," "toxin-free," or that plastic "gives you cancer / disrupts your hormones" about a person -- keep it to what the material does (avoids introducing named compounds), never a health verdict on the drinker. Sources: Sci. Reports 2025 (EDC leaching); PNAS/NIH nanoplastics in bottled water; stainless Ni/Cr, Kamerud 2013.$b$),
  ('concierge', 'Craft . Every contact point (the closures nuance)',
   $b$We do not stop at the bottle. Glass earns its place, but a real finding is that glass bottles can still pick up microplastics from PLASTIC-BASED PAINT ON CAPS that flakes -- so the cap, the seal, and every surface between the coffee and your hand get the same single question: does this introduce anything? If it does, it is out. MAY say: we vet closures and every contact surface, not just the bottle; glass earns the win and the closures have to earn it too. This is honest and it strengthens the "every point it touches" story. MUST NOT turn it into "so there are zero microplastics" -- the point is diligence at every surface, not an absolute. Source: ANSES 2024 (caps contaminate beverages with microplastics).$b$),
  ('all', 'Craft . The mark -- caffeine molecule = GT3 (factual)',
   $b$The GT3 identity ties to the caffeine molecule: caffeine (1,3,7-trimethylxanthine) is a purine -- a six-membered ring fused to a five-membered ring -- carrying THREE methyl groups at its nearest points. Three methyls, three 3s, written into the chemistry. MAY say: caffeine has three methyl groups -- three 3s -- which is the idea behind GT3; art meets chemistry. This is factual chemical structure, fair to describe. MUST NOT attach a health benefit to the molecule ("caffeine boosts X") beyond the plainly-known "caffeine is a stimulant." Keep it structural and brand-identity, not medical.$b$),
  ('all', 'Craft . HARD BOUNDARY -- no gene-expression / "net-positive" claims',
   $b$RETIRED FROM ALL OUTWARD COPY, highest liability: never say our coffee, materials, or process "positively affects gene expression," is "net-positive on your genes," "optimizes gene expression," is "nutrigenomically superior," or any phrasing that a food changes a person's genes/epigenetics to improve health or prevent disease. There IS early, mostly-laboratory research that food polyphenols interact with the epigenome, but human evidence is preliminary and correlational, no food is shown to affect human genes "only positively," and as worded it is an unsubstantiated structure/function claim edging into an illegal drug/disease claim. THE COMPLIANT REFRAME (use this instead): talk about what we DO NOT INTRODUCE -- "we do not add the endocrine-disrupting plasticizers or microplastics associated with plastic, so we are not introducing compounds known to interfere with hormone signaling" (a materials statement), and use general nutritive language -- "coffee and cocoa are natural sources of polyphenol antioxidants." If someone asks about the science directly, describe it honestly as emerging, early, mostly-laboratory research on polyphenols and the epigenome -- never as a benefit our product delivers. Also retire "detox," "toxin-free," and "non-toxic" as absolutes for the same reason. Sources: PMC9958838 (coffee epigenetics, evidence "extremely limited"); FDA structure/function claims; 21 CFR 101.93.$b$)
) as v(agent, title, body)
where not exists (select 1 from public.agent_knowledge k where k.title = v.title);

-- verify:
--   select count(*) from public.agent_knowledge where title like 'Craft .%' and active;  -- 7
